name: Mirror Public Repository

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Repository
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/GlazedBelmont/es-de-android-custom-systems"
          source_branch: "main"
          destination_repo: "git@github.com:admyrick/test.git"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
