name: Mirror Repository

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Mirror Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: https://${{ secrets.PAT_TOKEN }}@github.com/admyrick/test.git
          source_repo_url: https://github.com/GlazedBelmont/es-de-android-custom-systems.git
